### PR TITLE
Palindrome Number

### PR DESCRIPTION
**Pull request by harshita9621**

### CODE REVIEW

**Comment by harshita9621** [comment]
@shiv0408 Why this PR not showing in my hacktoberfest profile

**Comment by shiv0408** [comment]
@harshita9621 Check carefully, other PRs in this repo are showing up on hacktoberfest profile.

**Comment by shiv0408** [comment]
Reopen a PR I will accept again

**Comment by harshita9621** [comment]
Then what I  have to do

**Pull request merged**
